#! /bin/bash
echo "Enter first number: "
read a
echo "Enter second number: "
read b
echo "Addition: $(echo "$a + $b" | bc)"
echo "Subtraction : $(echo "$a - $b" | bc)"
echo "Multiplication: $(echo "$a * $b" | bc)"
echo "Division: $(echo "$a/$b" | bc)"
