#! /bin/bash
echo "Enter Ramesh's basic salary: "
read basic
da=$(echo "$basic * 0.40" | bc)
hra=$(echo "$basic * 0.30" | bc)
gross=$(echo "$basic + $da + $hra" | bc)
echo "Gross Salary : Rs. $gross"
